import augustus from "./img/Augustus.jpg"
import React from "react"
import arcadius from "./img/Arcadius.jpg"
import aurelian from "./img/Aurelian.png"
import caligula from "./img/Caligula.jpg"
import caracalla from "./img/Caracalla.jpg"
import claudius from "./img/Claudius.jpg"
import constantine from "./img/Constantine.jpg"
import domitian from "./img/Domitian.jpg"
import galienus from "./img/Galienusi.jpg"
import hadrian from "./img/Hadrian.jpg"
import marcus from "./img/Marcus.jpg"
import Phillipe from "./img/Phillipe.jpg"
import severus from "./img/Severus.jpg"
import tiberius from "./img/tiberius.jpg"
import traian from "./img/Traian.jpg"
import Vespasian from "./img/Vespasian.jpg"
const emperors =[augustus,arcadius,aurelian,caligula,caracalla,claudius,constantine,domitian,galienus,hadrian,marcus,Phillipe,severus,tiberius,traian,Vespasian]
const names = ["Augustus","Arcadius","Aurelianus","Caligula","Caracalla","Claudius","Constantine the great","Domitian","Galienus","Hadrian","Marcus Aurelius","Phillipe Arabus","Septimius Severus","Tiberius","Traianus","Vespasianus"]
export {emperors,names}